#ifndef ELEV_PORT_H_
#define ELEV_PORT_H_

#define MAX_COMMAND_SIZE 100

#define INIT_COMMAND 1
#define SET_MOTOR_DIRECTION_COMMAND 2
#define SET_DOOR_OPEN_LAMP_COMMAND 3
#define GET_OBSTRUCTION_SIGNAL_COMMAND 4
#define GET_STOP_SIGNAL_COMMAND 5
#define SET_STOP_LAMP_COMMAND 6
#define GET_FLOOR_SENSOR_SIGNAL_COMMAND 7
#define SET_FLOOR_INDICATION_COMMAND 8
#define GET_BUTTON_SIGNAL_COMMAND 9
#define SET_BUTTON_LAMP_COMMAND 10

#endif
